# The proxy server adds the X_REQUEST_START header for queue time calculations
proxy: npx judoscale-adapter-proxy-server

# Run with --noreload to avoid multiple server processes (and multiple Judoscale reporters)
web: gunicorn celery_sample.wsgi:application --preload

# Run celery with heroku
worker: celery -A celery_sample worker --loglevel=INFO -Q celery -E
