# The proxy server adds the X_REQUEST_START header for queue time calculations
proxy: npx judoscale-adapter-proxy-server

# Run with --noreload to avoid multiple server processes (and multiple Judoscale reporters)
web: DYNO=web.1 poetry run gunicorn django_rq_sample.wsgi:application --preload
worker: DYNO=worker.1 poetry run python manage.py rqworker default low
worker_high: DYNO=worker_high.1 poetry run python manage.py rqworker high
